version: "3.7"
services:
  db:
    image: postgres:14-alpine
    container_name: pasta_xiana_services
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="${PG_DB_NAME}","${PG_TEST_DB_NAME}"
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes:
  db-data:
