name: "Run tests"

on:
  push:
    branches-ignore:
      - "WIP*"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8.0.292"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.693 
          lein: 2.9.1

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test